### ISSUE TITLE
Unsupported argument type: NilClass. Construct an Arel node instead.

### ISSUE THREAD

**Issue by metalsoft10** [npezza93/chat#2]
Arel::Visitors::UnsupportedVisitError in Visitors#index
Showing /root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/chat-0.2.0/app/views/chat/conversations/_index.html.haml where line #1 raised:

Unsupported argument type: NilClass. Construct an Arel node instead.

![image](https://user-images.githubusercontent.com/12839970/28528051-e1011d74-708c-11e7-882e-5632b21d0f44.png)

**Comment by metalsoft10** [comment]
@chat_list ||= Chat::Conversation.joins(:users).group("chat_sessions.conversation_id").select(:id, group_concat).merge(current_user.conversations).order(created_at: :desc)
 i dont know what error 
but when i removed this line error gone but no chat shows

**Comment by npezza93** [comment]
Looking at your screenshot, it appears you are running chat 0.2.0. Do you mind updating to 1.0.0 and see if that fixes the issue? I also saw your other issue, and I'll  update the gemspec with haml as a dependency.

**Comment by metalsoft10** [comment]
@npezza93  thank you i will try right now

**Comment by metalsoft10** [comment]
thank you almost work i will try from clean app again 
its work but no send and receive MSG 
just create the conversation may be my fault

**Comment by metalsoft10** [comment]
Cannot render console from ' MY IP '! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Started GET "/cable/"[non-WebSocket] for 156.216.141.114 at 2017-07-24 22:06:03 +0000
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Keep-Alive, HTTP_UPGRADE: )
Finished "/cable/"[non-WebSocket] for 156.216.141.114 at 2017-07-24 22:06:03 +0000

must refresh to show msg

**Comment by npezza93** [comment]
That is not an issue caused by this gem. That is an ActionCable config issue. Make sure your cable.yml is setup properly.

**Comment by metalsoft10** [comment]
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Keep-Alive, HTTP_UPGRADE: )
needed this line at 
application.rb

config.action_cable.allowed_request_origins = [/http:\/\/*/, /https:\/\/*/]
now i have an other error 
WebSocket connection to 'ws://localhost:3000/cable' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

i put this line 
config.action_cable.url = 'ws://localhost:3000/cable'
not worked 
my app is development 
cable.yml
development:
adapter: async
using Clearance as sign in 
  Chat.setup do |config|
  
  config.signed_in = :signed_in?

  
  config.logged_in_check = :require_login

  config.user_avatar = :avatar

  config.perform_method = :perform_now
end

**Comment by npezza93** [comment]
That is also not an issue with this gem. Please use either StackOverflow for help or refer to the dummy app in the test dir as reference on how to setup ActionCable.

**Comment by metalsoft10** [comment]
ok thank you all i want was make it as help for other if they get same errors
